Add dependent container restarting

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -21,6 +21,7 @@ case "${DOCKER_SOCK}" in
 esac
 
 AUTOHEAL_CONTAINER_LABEL=${AUTOHEAL_CONTAINER_LABEL:-autoheal}
+AUTOHEAL_CONTAINER_LABEL=${AUTOHEAL_CONTAINER_LABEL:-autoheal_depends}
 AUTOHEAL_START_PERIOD=${AUTOHEAL_START_PERIOD:-0}
 AUTOHEAL_INTERVAL=${AUTOHEAL_INTERVAL:-5}
 AUTOHEAL_DEFAULT_STOP_TIMEOUT=${AUTOHEAL_DEFAULT_STOP_TIMEOUT:-10}
@@ -48,12 +49,46 @@ get_container_info() {
   docker_curl "$url"
 }
 
+get_dependent_container_info() {
+  local label_filter
+  local url
+  local dependency_name="$1"
+
+  # Set container selector
+  label_filter=",\"label\":\[\"${AUTOHEAL_DEPENDENT_CONTAINER_LABEL}=${dependency_name}\"\]"
+
+  url="${HTTP_ENDPOINT}/containers/json?filters=\{${label_filter}\}"
+  docker_curl "$url"
+}
+
 # shellcheck disable=2039
 restart_container() {
   local container_id="$1"
   local timeout="$2"
+  local container_name="$3"
 
   docker_curl -f -X POST "${HTTP_ENDPOINT}/containers/${container_id}/restart?t=${timeout}"
+  sleep 10
+  
+  get_dependent_container_info "$container_name" | \
+    jq -r "foreach .[] as \$CONTAINER([];[]; \$CONTAINER | .Id, .Names[0], ${STOP_TIMEOUT})" | \
+    while read -r CONTAINER_ID && read -r CONTAINER_NAME && read -r TIMEOUT
+  do
+    # shellcheck disable=2039
+    CONTAINER_SHORT_ID=${CONTAINER_ID:0:12}
+    DATE=$(date +%d-%m-%Y" "%H:%M:%S)
+
+    if [ "$CONTAINER_NAME" = "null" ]
+    then
+      echo "$DATE Container name of (${CONTAINER_SHORT_ID}) is null, which implies container does not exist - don't restart" >&2
+    else
+      echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be unhealthy - Restarting container now with ${TIMEOUT}s timeout"
+      if ! restart_container "$CONTAINER_ID" "$TIMEOUT" "$CONTAINER_NAME"
+      then
+        echo "$DATE Restarting container $CONTAINER_SHORT_ID failed" >&2
+      fi
+    fi
+  done
 }
 
 # SIGTERM-handler
@@ -88,7 +123,7 @@ if [ "$1" = "autoheal" ] && [ -e "$DOCKER_SOCK" ];then
         echo "$DATE Container name of (${CONTAINER_SHORT_ID}) is null, which implies container does not exist - don't restart" >&2
       else
         echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be unhealthy - Restarting container now with ${TIMEOUT}s timeout"
-        if ! restart_container "$CONTAINER_ID" "$TIMEOUT"
+        if ! restart_container "$CONTAINER_ID" "$TIMEOUT" "$CONTAINER_NAME"
         then
           echo "$DATE Restarting container $CONTAINER_SHORT_ID failed" >&2
         fi
